raphael: add telephony-ext to boot jars
* network settings crash without this with the following error:

Caused by:java.lang.NoClassDefFoundError: Failed resolution of: Lorg/codeaurora/internal/IExtTelephony;

Signed-off-by: Ayush Dubey <ayushdubey70@gmail.com>